block-13/13-01/symfony_blog/src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 128)]
    private ?string $title = null;

    #[ORM\Column(length: 128)]
    private ?string $alias = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publish_date = null;

    #[ORM\Column(length: 32)]
    private ?string $status = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?PostCategory $category = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?PostCover $cover = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?PostCategory
    {
        return $this->category;
    }

    public function setCategory(?PostCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCover(): ?PostCover
    {
        return $this->cover;
    }

    public function setCover(?PostCover $cover): self
    {
        $this->cover = $cover;

        return $this;
    }
}

block-13/13-01/symfony_blog/src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostsController extends AbstractController
{
	#[ Route( '/', name: 'homepage', methods: ['GET', 'HEAD'] ) ]
    public function index( PostRepository $postRepository ) : ?Response
    {
		$posts = $postRepository -> getPosts();
        return $this -> render( 'posts/index.html.twig',
		[
            'posts' => $posts,
			'next_offset' => PostRepository::PAGE_COUNT,//min( count( $posts ), PostRepository::PAGE_COUNT ),
			'current_page' => 1,
        ]);
    }

	#[ Route( '/list/{offset}', name: 'posts_list', methods: ['GET', 'HEAD'] ) ]
	public function list( int $offset, PostRepository $postRepository ) : ?Response
	{
		$posts = $postRepository -> getPosts( $offset );
		$count_posts = $postRepository -> getCountPosts ();
		return $this->render( 'posts/list.html.twig',
			[
				'posts' => $posts,
				'prev_offset' => $offset - PostRepository::PAGE_COUNT,
				'next_offset' => $offset + PostRepository::PAGE_COUNT,//min( count( $posts ), $offset + PostRepository::PAGE_COUNT ),
				'current_page' => ceil( $offset / PostRepository::PAGE_COUNT ) + 1,
				'count_posts' => $count_posts,
			]
		);
	}

	#[ Route( '/category/{id}-{category}', name: 'posts_category', methods: ['GET', 'HEAD'] ) ]
	public function index_category( int $id, string $category, PostRepository $postRepository ) : ?Response
	{
		$posts = $postRepository -> getCategoryPosts( $id );
		return $this -> render( 'posts/category.html.twig',
		[
			'posts' => $posts,
			'next_offset' => PostRepository::PAGE_COUNT,//min( count( $posts ), PostRepository::PAGE_COUNT ),
			'current_page' => 1,
			'current_id' => $id,
			'current_category' => $category,
		]);
	}

	#[ Route( '/category/{id}-{category}/list/{offset}', name: 'posts_category_list', methods: ['GET', 'HEAD'] ) ]
	public function index_category_list( int $id, string $category, int $offset, PostRepository $postRepository ) : ?Response
	{
		$posts = $postRepository -> getCategoryPosts( $id, $offset );
		$count_posts = $postRepository -> getCountPosts( $id );
		return $this -> render( 'posts/category_list.html.twig',
		[
			'posts' => $posts,
			'prev_offset' => $offset - PostRepository::PAGE_COUNT,
			'next_offset' => $offset + PostRepository::PAGE_COUNT,//min( count( $posts ), $offset + PostRepository::PAGE_COUNT ),
			'current_page' => ceil( $offset / PostRepository::PAGE_COUNT ) + 1,
			'current_id' => $id,
			'current_category' => $category,
			'count_posts' => $count_posts,
		]);
	}

	#[ Route( '/post/{id}-{alias}', name: 'post_view', methods: ['GET', 'HEAD'] ) ]
	public function view( int $id, string $alias, PostRepository $postRepository ) : ?Response
	{
		try
		{
			if( !$post = $postRepository -> getPost( $id ) )
			{
				throw new \Exception( 'Error 404. Page not found' );
			}
			$random_posts = $postRepository -> getRandomPosts();

			if( $post->getAlias() !== $alias )
			{
				return $this -> redirectToRoute(
					'post_view',
					[
						'id'    => $post->getId(),
						'alias' => $post->getAlias(),
					],
					301
				);
			}

			return $this -> render( 'posts/view.html.twig',
			[
				'post' => $post,
				'random_posts' => $random_posts,
			]);
		}
		catch( \Exception $error )
		{
			return $this -> render( 'posts/404.html.twig',
			[
				'error' => $error,
			]);
		}

//		$post = $postRepository -> getPost( $id );
//		$random_posts = $postRepository -> getRandomPosts();
//
//		if( !$post )
//		{
//			throw $this->createNotFoundException( 'Post with #' . $id . ' not found' );
//		}
//
//		if( $post->getAlias() !== $alias )
//		{
//			// на випадок некоректного alias у URI -> переходимо до коректної сторінки
//			return $this->redirectToRoute(
//				'post_view',
//				[
//					'id'    => $post->getId(),
//					'alias' => $post->getAlias(),
//				],
//				301
//			);
//		}
//		return $this -> render( 'posts/view.html.twig',
//		[
//			'post' => $post,
//			'random_posts' => $random_posts,
//		]);
	}
}

block-13/13-01/symfony_blog/templates/posts/404.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <main class="main _container">
        <div class="error_wrapper">
            <p class="error">Error 404 <br> Page not found</p>
        </div>
    </main>
{% endblock %}

block-13/13-01/symfony_blog/templates/posts/index.html.twig
{% extends 'base.html.twig'%}

{% block body %}
<main class="main _container">
    <section class="main__section-title">
        <h4 class="title-small">Explore.Discover.Share</h4>
        <h1 class="title-main">Start Your Journey</h1>
    </section>
    <section class="slider-main">
        <div class="slider-main__wrapper">
            <picture class="slider-main__image">
                <!--
                1200px = 75rem
                1199px = 74.94rem
                992px = 57.5rem
                460px = 28.75rem
                -->
                <source media="(max-width: 28.75rem)" srcset="{{ asset( '/images/460px/image-3.webp' ) }}" type="image/webp">
                <source media="(max-width: 28.75rem)" srcset="{{ asset( '/images/460px/image-3.jpg' ) }}" type="image/jpeg">
                <source media="(max-width: 57.5rem)" srcset="{{ asset( '/images/690px/image-3.webp' ) }}" type="image/webp">
                <source media="(max-width: 57.5rem)" srcset="{{ asset( '/images/690px/image-3.jpg' ) }}" type="image/jpeg">
                <source media="(max-width: 74.94rem)" srcset="{{ asset( '/images/910px/image-3.webp' ) }}" type="image/webp">
                <source media="(max-width: 74.94rem)" srcset="{{asset( '/images/910px/image-3.jpg' )  }}" type="image/jpeg">
                <source media="(min-width: 75rem)" srcset="{{ asset( '/images/1110px/image-3.webp' ) }}" type="image/webp">
                <source media="(min-width: 75rem)" srcset="{{ asset( '/images/1110px/image-3.jpg' ) }}" type="image/jpeg">
                <img src="{{ asset( '/images/460px/image-3.jpg' ) }}" alt="Mountains and lake">
            </picture>
            <div class="slider__meta">
                <h3 class="slider-main__category category">
                    <a class="category__link" href="#">Nature</a>
                </h3>
                <h2 class="slider-main__title title-post">
                    <a class="title-post__link" href="#">Explore New Places</a>
                </h2>
                <a class="link-post" href="#">read more</a>
            </div>
            <div class="slider-main__control">
                <span class="control-btn control-btn--left">&lt;</span>
                <span class="control-btn control-btn--right">&gt;</span>
            </div>
        </div>
    </section>
    {% if posts|length > 0 %}
    <section class="main__grid grid screen">
        <div class="grid__wrapper">
        {% for key in posts|keys %}
            {% if key == 0 or key == 4 or key == 8  %}
            <div class="grid__item grid__item--big">
                <picture>
                    <source media="(max-width: 28.75rem)" srcset="{{ asset('/images/460px/' ~ posts[key].cover.filename ~ '.webp') }}" type="image/webp">
                    <source media="(max-width: 28.75rem)" srcset="{{ asset('/images/460px/' ~ posts[key].cover.filename ~ '.jpg') }}" type="image/jpeg">
                    <source media="(max-width: 57.5rem)" srcset="{{ asset('/images/690px/' ~ posts[key].cover.filename ~ '.webp') }}" type="image/webp">
                    <source media="(max-width: 57.5rem)" srcset="{{ asset('/images/690px/' ~ posts[key].cover.filename ~ '.jpg') }}" type="image/jpeg">
                    <source media="(max-width: 74.94rem)" srcset="{{ asset('/images/910px/' ~ posts[key].cover.filename ~ '.webp') }}" type="image/webp">
                    <source media="(max-width: 74.94rem)" srcset="{{ asset('/images/910px/' ~ posts[key].cover.filename ~ '.jpg') }}" type="image/jpeg">
                    <source media="(min-width: 75rem)" srcset="{{ asset('/images/1110px/' ~ posts[key].cover.filename ~ '.webp') }}" type="image/webp">
                    <source media="(min-width: 75rem)" srcset="{{ asset('/images/1110px/' ~ posts[key].cover.filename ~ '.jpg') }}" type="image/jpeg">
                    <img src="{{ asset('/images/460px/' ~ posts[key].cover.filename ~ '.jpg') }}" alt="{{ posts[key].cover.title }}">
                </picture>
            {% else %}
            <div class="grid__item">
                <picture>
                    <source media="(max-width: 28.75rem)" srcset="{{ asset('/images/460px/' ~ posts[key].cover.filename ~ '.webp') }}" type="image/webp">
                    <source media="(max-width: 28.75rem)" srcset="{{ asset('/images/460px/' ~ posts[key].cover.filename ~ '.jpg') }}" type="image/jpeg">
                    <source media="(max-width: 690rem)" srcset="{{ asset('/images/690px/' ~ posts[key].cover.filename ~ '.webp') }}" type="image/webp">
                    <source media="(max-width: 690rem)" srcset="{{ asset('/images/690px/' ~ posts[key].cover.filename ~ '.jpg') }}" type="image/jpeg">
                    <source media="(min-width: 690rem)" srcset="{{ asset('/images/690px/' ~ posts[key].cover.filename ~ '.webp') }}" type="image/webp">
                    <source media="(min-width: 690rem)" srcset="{{ asset('/images/690px/' ~ posts[key].cover.filename ~ '.jpg') }}" type="image/jpeg">
                    <img src="{{ asset('/images/460px/' ~ posts[key].cover.filename ~ '.jpg') }}" alt="{{ posts[key].cover.title }}">
                </picture>
            {% endif %}
                <a class="grid__post-link" href="{{ path( 'post_view', { id: posts[key].id, alias: posts[key].alias } ) }}"></a>
                <div class="grid__meta">
                    <h3 class="grid__category category">
                        <a class="category__link" href="{{ path( 'posts_category', { id: posts[key].category.id, category: posts[key].category.title  } ) }}">{{ posts[key].category.title }}</a>
                    </h3>
                    <h2 class="grid__title title-post">
                        <a class="title-post__link" href="{{ path( 'post_view', { id: posts[key].id, alias: posts[key].alias } ) }}">{{ posts[key].title }}</a>
                    </h2>
                    <div class="grid__post-info">
                        <a class="author-post" href="#">{{ posts[key].author.firstname ~ ' ' ~ posts[key].author.lastname }}</a>
                        <time class="date-post" datetime="{{ posts[key].publishDate|date('c') }}">{{ posts[key].publishDate|date('F d, Y') }}</time>
                    </div>
                    <a class="grid__link link-post" href="{{ path( 'post_view', { id: posts[key].id, alias: posts[key].alias } ) }}">read more</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </section>
    {% else %}
    <section class="main__grid grid screen">
        <div class="grid__wrapper">
            <div class="grid__item grid__item--big">
                <p class="grid__title title-post title-post--small">No artical</p>
            </div>
        </div>
    </section>
    {% endif %}
    <nav class="pagination">
        <ul class="pagination__list">
            <li class="pagination__item pagination__current"><span class="pagination__link">{{ current_page }}</span></li>
            <li class="pagination__item"><a class="pagination__link" href="{{ path( 'posts_list', { offset: next_offset } ) }}">>></a></li>
        </ul>
    </nav>
{#    <div class="print">#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-2.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-2.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-2.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Turn Heads with This Outfit</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 17, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-1.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-1.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-1.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Summer Vacation Ideas</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 16, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-7.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-7.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-7.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Photo Session in the Woods</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 15, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-15.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-15.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-15.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Charm and Magic</p>#}
{#            <p><span class="print__author">April Smtih</span><span class="print__time">January 14, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-13.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-13.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-13.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Morning Exercises</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 13, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-3.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-3.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-3.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Explore New Places</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 12, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-11.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-11.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-11.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Rainy Days</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 11, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-10.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-10.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-10.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Hot Air Balloons</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 10, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-9.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-9.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-9.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">The Road</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 9, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-8.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-8.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-8.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Trip to Sea</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 8, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-4.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-4.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-4.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Travel Days</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 7, 2022</span></p>#}
{#        </div>#}
{#        <div class="print__item">#}
{#            <picture>#}
{#                <source srcset="images/460px/image-5.webp" type="image/webp">#}
{#                <source srcset="images/460px/image-5.jpg" type="image/jpeg">#}
{#                <img src="images/460px/image-5.jpg" alt="Mountains and lake">#}
{#            </picture>#}
{#            <p class="print__title">Wearing White Dress</p>#}
{#            <p><span class="print__author">April Smith</span><span class="print__time">January 6, 2022</span></p>#}
{#        </div>#}
{#    </div>#}
</main>
{% endblock %}